### ISSUE TITLE
Have you tried using dynamic in place of object in the dictionary?

### ISSUE THREAD

**Issue by moggoly** [joseftw/JOS.STJ.DictionaryStringObjectJsonConverter#1]
I had a similar issue with the Mandrill (Mailchimp) API, and found that using Dictionary<string, dynamic> solved all my issues around serialization. We're stuck using Newtonsoft.Json for other reasons, but I seem to remember that this also worked fine with System.Text.Json.

**Comment by joseftw** [comment]
Hello @moggoly !
No, I had not tried using dynamic before, but I have now! :) 
For my use case, it does not work (see image), but if you only use System.Text.Json then I think it might work. The problem in my case was to get Newtonsoft to serialize the dictionary created by System.Text.Json

![Capture](https://user-images.githubusercontent.com/1232096/91064584-b6073b00-e62f-11ea-8dbf-ce45d68c5ca0.PNG)
