### ISSUE TITLE
If we have an IEnumerable as data the code throws System.Reflection.TargetParameterCountException

### ISSUE THREAD

**Issue by hartmark** [joseftw/JOS.STJ.DictionaryStringObjectJsonConverter#2]
I don't know if this is maintained or if this is just a repo to show-case the converter. However I wanted to share our finding of an issue in the code.

We use this code in jwt-dotnet and had an issue where an exception is thrown if an IEnumerable is handled.

See this PR for the fix:
https://github.com/jwt-dotnet/jwt/pull/439

BR,
Harre

**Comment by joseftw** [comment]
Thanks!
If I understand you correctly, what's missing is a case for `IEnumerable enumerable` in `DictionaryStringObjectJsonConverter.`?

If yes, I will add some tests and implement the fix :)

**Comment by hartmark** [comment]
Yes, that is the fix. This code, do you have it as a nuget we can use instead of copying the code?

**Comment by joseftw** [comment]
I see. I will see if I can publish a nuget soon. However, another workaround would be to pass in a `JsonSerializerOptions` that doesn't contain the `DictionaryStringObjectJsonConverter` at all. By doing that you will use the built in logic for serializing to json.

There's no point imo to use `DicitonaryStringObjectJsonConverter`when serializing, it's only useful when deserializing.

Would that work for you?

**Comment by hartmark** [comment]
Yes, it works perfectly to just use this converter for reading serialized data and fallback to the built in logic for serializing.

Edit: It's no longer relevant as you don't have Serialization in your code any more
~~PS. An array implements IEnumerable so your code can do the fix by just replacing:~~
~~`case object[] arr`~~
~~with:~~
~~`case IEnumerable arr`~~

**Comment by hartmark** [comment]
I see you have now updated this repo with more documentation about this converter. Well done!

Is there any issue upstream on dotnet-repo for making this converter included into System.Text.Json? I think it would be good to have this in upstream so the behaviour is similar to JSON.net

**Comment by joseftw** [comment]
Yeah I'm doing some preparation so I can release it as a nuget package :)

Yeah I agree, this should be built in, and I think that MS can do a better job than me when it comes to this converter!

**Comment by joseftw** [comment]
Code is now published as a nuget package.

```dotnet add package JOS.SystemTextJson.DictionaryStringObject.JsonConverter```

**Comment by hartmark** [comment]
Thanks!

Can you change the targetframework so it matches System.Text.Json so we can use it from .net fw 4.6.1 and newer.

Then a link from here to nuget.org and one from nuget to this repo would be nice to get more info about the package.

**Comment by joseftw** [comment]
It now targets netstandard 2.0 :)

**Comment by hartmark** [comment]
Cool!

I'll change the code to use the nugget instead of the copied code I copied from here 😀

**Comment by joseftw** [comment]
Awesome, let me know if you run into any problems :)
