### ISSUE TITLE
Source code package?

### ISSUE THREAD

**Issue by abatishchev** [joseftw/JOS.STJ.DictionaryStringObjectJsonConverter#3]
Hi!
I'd love to use your awesome library in [Jwt.Net](https://github.com/jwt-dotnet/jwt/) but hesitant to add it as a runtime dependency, as it would be the first one (besides Json.Net before, and System.Text.Json since recently). Right now the library is mostly self-contained so I don't want to open the Pandora's box. Here's the discussion: https://github.com/jwt-dotnet/jwt/pull/442.
Would you consider shipping it as a source code package? I'd add it as a build-time dependency in no time.

**Comment by joseftw** [comment]
Hello! Sure! How would I do that? I don't think I've ever encountered that term before when it comes to nuget... 😁
